sudo: false
language: python

install:
    - pip install tox

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: TOXENV=py35
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=py27
  allow_failures:
    - python: pypy

script:
    - tox
